language: node_js
node_js: lts/*
install:
- make init
script:
- make lint
- make test
deploy:
  provider: heroku
  api_key:
    secure: MbFe5/nH2KpL4PB1KsnqcezKakjxOk2G2tnlJgJnBrt5YLYCDUK3oD3PunIKQDbQg2wlkLVWCZFyfogqAzwRJqsAWpqzRw7gN4z1wzFHnM0mn6rhjffwYdQ58vI6JuSLP948Fu736ThZWYQtFUDi+73I3Pxm937wX50Fe7oVOy4gr1OfRgr7ituMbBHI5pv621gE+nokhCT4P0d/lv/aECXIxlz0wZB7IMSQ4mB9RMvVxS34GZ5TS0/b8LtBhopZ8OTSKsTN2YQgoixGFMYsbKUH1I9xP+6mFNAcx7bEGnNxz80qZKjtH8BlScPHTlYdx/FMr7le0+n/IoYABlVXWq2c9NUs7LS8gkzrwfJfrZkTm698JGHSgQE+50uvfMHz7BS5RbFid8vw+KIHyOKbRzs7sA3lrydRHhYNJNKXEx42B4h2tVsPPxyVQgc2UC462h+TcVOKUjKcX7j9oQzV9jkFtjH9rrpVmveuw87oUfv31G4htl8aryIEQGz3yWJULWFwLP+hu7mMbYUdypiEKKWss/N4gKGTmhRAAsDYjSst1rZUf6MRyJkbeZhFjO3thwDZq9EHTyKfkePCgDpizdD73dKt+dVCwMmLkb7FKY52AeTrOyPs2LubhQIjgLKlnwbCdAaR239idbkXUmdxW6VmpHIyNUkiImro/RPwQGI=
  app: powerful-brook-25233
  skip_cleanup: true
