language: node_js
node_js: lts/*
install:
- make init
script:
- make lint
- make test
deploy:
  provider: heroku
  api_key:
    secure: LspjqDBAdlehenfH/erV8mYMfmf9r2nv3vxXbdHTGufo5v9K28xQjYcPkOEYCunNLTktBv4JqBCzuLwhTlTHvIY/5tkou81q6URSntTXz/21t3RUMmJl+G/8PXamJLZkpiH8xq8pQ9S6wlcJTaR1WndCnDHW9LfH4Rwt0wtxXWePec8et43qN3Raxg3hRFmQ40Whwz30Ct0K2K2koRslV2MylP6m2o2kBFBdXePRxdbf/eP4wF3oEKYaQvGsrIe0T0LwjcWyHqdX114577HD8PrrFopjHvAriVZWbs8yJ5l2WMKfVQTwPhOAcXQf4lwXR7cJN6sdW/gBAtWjR5b9L/aPmgPtaFzSYybpAk9SbnvxNt2DugzSluvyq9Lt5P9ln+1H3sWkaNNjhVdEtMJt5kIm9OO9YWpf2rOvvuMegCTIyh0Yl7WTnaTgjfMCmwLAaHZr329KePv9puYa43H6si2XlSC6wjtGx8hcxiPUqXzDx2+95kOcMMdz6whiA19rTwL573BN1/55gio2RIW6p0j9K6YsZe5epFdNKV3sq6V/Fe/q+XTW2sFHVi94acsauCSusmsi6c91cbGh8MfaCiiYXzWjnktHiFnUGsIFbozciVzNo7p7q+bAohrT0zJH06YFfRIfA3NQKwm/VJAzmvmkcQnjV3WkqmnT6jx0mLE=
  app: ahoward1024todo
  skip_cleanup: true
