language: node_js
node_js:
  "lts/*"
install:
- make init
script:
- make lint
- make test
deploy:
  provider: heroku
  api_key:
    secure: l47XiPGynHU+BhapJNWvXTW72ajhauwBe/MbZSFHqVmXd1fbnImArcFf2LMVjIxXLBkYpUFPe2Z7whDtZcgkgA6ZERvQXsngNIecKiT+kJAip45tpzR7TNENBbRG2eK6IUAi0yAA2AsGPCJrgSfsflqenBoW386NXA8SYdTTtE/nd4gng91p83uUTQ32N7RjKGO1mdx1Z7NHFo6xwmtzF2gmX4ML0AMq8NIAD77zzHZ0y3tK1qPv2OylJoNZ8F2W1gnDOHJldoncJpWU9dimMrUsr7xa7fnZ3Clx8cfS2FsXaCbGmZpiw3x+nOsZW2RC+kTHDwsE268qilq93qfzey+/ZdoM7EwcAWjaLYaotG1KTS0CM+fiRmLAnquIWjWE1BDPtqJviOBFCrXPbmQEvunQRIGuNgdDoB+3t6QBoz87yxdiOGVWClcPDzHvW6gMlLzHKz/xRq3vpX0lxIhQI/ClQnDuO6XoaZey6xfv7N00HpofVwrikSXnQJv1SktBdl1R3t5SweExMGz+BBeqPeIzrqCJ8j0bWlvgkjQMm3ssMmDbUmc77WA908Q7epSnLwuRmUKz+Whd49gnpfE4rQz3vIGT3HnvOWYOz6aOKgs20jj3HhIHPfQa3+Tny4nffgxqZYe2zOm7CopfkhjItk7YwygDkS5urbs+ZcI9z5I=
  app: powerful-brook-25233
  skip_cleanup: true
